### ISSUE TITLE
Is there a settings or tip to improve the response time?

### ISSUE THREAD

**Issue by jrichardsz** [solyarisoftware/voskJs#11]
First I want to thank you for your time to develop this client.

Your toolkit worked with buffer from sockets. I tried with another [library](https://github.com/alphacep/vosk-api/issues/1504#issuecomment-1913955137) without success

I just wonder if there is a setting or tip to decrease the response time. Currently is 4 or 5 seconds in localhost tests. I need a approximately response time of 1 or 2 seconds.

![image](https://github.com/solyarisoftware/voskJs/assets/3322836/6b2f9806-6e87-48a4-87e0-6e0aec5afea2)

I tried to instance the recognizer (my local fork) before and the send it on each recognition but the time is the same :( 

```
const recognizer = createRecognizer( model, {sampleRate, grammar, alternatives, words} )
const result1 = await transcriptFromBufferWithPreLoadRecognizer(data, recognizer)
const resultN = await transcriptFromBufferWithPreLoadRecognizer(data, recognizer)
```

Also according to my tests, the **recognizer.acceptWaveform** method is about 2 or 3 seconds.

Thanks

**Comment by solyarisoftware** [comment]
Hi. 
Honestly this appears to not be an issue. 

You didn't supply useful elements (code & data) to evaluate response time.
Anyway, maybe the question could be better to shared in the discussions sections.
